# Generated by Django 5.0.14 on 2026-04-24 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Brand name (e.g. Apple, Samsung)', max_length=200)),
                ('model', models.CharField(help_text='Model name (e.g. iPhone 14 Pro Max)', max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=350, unique=True)),
                ('display_resolution', models.CharField(blank=True, default='', max_length=200)),
                ('os', models.CharField(blank=True, default='', max_length=200, verbose_name='Operating System')),
                ('processor', models.CharField(blank=True, default='', max_length=300)),
                ('chipset', models.CharField(blank=True, default='', max_length=300)),
                ('gpu', models.CharField(blank=True, default='', max_length=300, verbose_name='GPU')),
                ('memory', models.CharField(blank=True, default='', max_length=200)),
                ('storage', models.CharField(blank=True, default='', help_text='e.g. 128 GB', max_length=200)),
                ('ram', models.CharField(blank=True, default='', help_text='e.g. 6 GB', max_length=200)),
                ('primary_camera', models.CharField(blank=True, default='', max_length=500)),
                ('secondary_camera', models.CharField(blank=True, default='', max_length=500)),
                ('loud_speaker', models.CharField(blank=True, default='', max_length=200)),
                ('audio_jack', models.CharField(blank=True, default='', max_length=200)),
                ('sensors', models.TextField(blank=True, default='')),
                ('battery', models.CharField(blank=True, default='', max_length=300)),
                ('colors', models.CharField(blank=True, default='', max_length=500)),
                ('price', models.CharField(blank=True, default='', help_text='e.g. ₹79,900', max_length=100)),
                ('img_url', models.URLField(blank=True, default='', max_length=1000)),
            ],
            options={
                'verbose_name': 'Smartphone',
                'verbose_name_plural': 'Smartphones',
                'ordering': ['name', 'model'],
            },
        ),
    ]
