# Generated by Django 5.0.14 on 2026-04-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_smartphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='is_best_seller',
            field=models.BooleanField(default=False, help_text="Show in 'Best Selling Phones' section on home page", verbose_name='Best Seller'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='is_latest',
            field=models.BooleanField(default=False, help_text="Show in 'Latest Phones' section on home page", verbose_name='Latest Phone'),
        ),
    ]
